#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
: "$RED"

banner "A-NAS v1.0.1 RC provisioning"

stage "Verify the release, network, and experimental disk"
[[ $EUID -eq 0 ]] || { warn "run this wizard as root"; exit 1; }

SOURCE_RELEASE=${SOURCE_RELEASE:-}
RELEASE_ID=${RELEASE_ID:-}
SMB_INTERFACE=${SMB_INTERFACE:-}
EXPECTED_DISK_WWN=${EXPECTED_DISK_WWN:-}
EXPECTED_DISK_SERIAL=${EXPECTED_DISK_SERIAL:-}
EXPECTED_DISK_SIZE_BYTES=${EXPECTED_DISK_SIZE_BYTES:-500107862016}

[[ -n "$SOURCE_RELEASE" ]] || ask SOURCE_RELEASE "Source release path:"
[[ -n "$RELEASE_ID" ]] || ask RELEASE_ID "Immutable root release ID:"
[[ -n "$SMB_INTERFACE" ]] || ask SMB_INTERFACE "Trusted LAN interface:"
[[ -n "$EXPECTED_DISK_WWN" ]] || ask EXPECTED_DISK_WWN "Expected experimental disk WWN:"
[[ -n "$EXPECTED_DISK_SERIAL" ]] || ask EXPECTED_DISK_SERIAL "Expected experimental disk serial:"

SOURCE_RELEASE=$(readlink -f -- "$SOURCE_RELEASE")
[[ -d "$SOURCE_RELEASE" ]] || { warn "source release is missing"; exit 1; }
[[ "$RELEASE_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { warn "release ID is invalid"; exit 1; }
[[ "$SMB_INTERFACE" =~ ^[A-Za-z0-9_.:-]+$ ]] || { warn "SMB interface is invalid"; exit 1; }
ip link show dev "$SMB_INTERFACE" >/dev/null

stable_disk="/dev/disk/by-id/wwn-$EXPECTED_DISK_WWN"
[[ -b "$stable_disk" ]] || { warn "stable experimental disk identity is missing: $stable_disk"; exit 1; }
resolved_disk=$(readlink -f -- "$stable_disk")
actual_wwn=$(udevadm info --query=property --name="$resolved_disk" | sed -n 's/^ID_WWN=//p')
actual_serial=$(udevadm info --query=property --name="$resolved_disk" | sed -n 's/^ID_SERIAL_SHORT=//p')
actual_size=$(lsblk -dn -b -o SIZE "$resolved_disk")
[[ "$actual_wwn" == "$EXPECTED_DISK_WWN" ]] || { warn "disk WWN changed"; exit 1; }
[[ "$actual_serial" == "$EXPECTED_DISK_SERIAL" ]] || { warn "disk serial changed"; exit 1; }
[[ "$actual_size" == "$EXPECTED_DISK_SIZE_BYTES" ]] || { warn "disk capacity changed"; exit 1; }
if lsblk -nrpo MOUNTPOINTS "$resolved_disk" | grep -q '[^[:space:]]'; then
  warn "experimental disk or a child is mounted"
  exit 1
fi
if swapon --noheadings --raw --show=NAME | grep -Fxq "$resolved_disk"; then
  warn "experimental disk is active swap"
  exit 1
fi

say "Source release: $SOURCE_RELEASE"
say "Root release ID: $RELEASE_ID"
say "SMB interface: $SMB_INTERFACE"
say "Disk: $resolved_disk, WWN $actual_wwn, serial $actual_serial, size $actual_size"
wipefs --no-act "$resolved_disk" || true
confirm "Do these values match the intended RC and disposable experimental disk?" || exit 1

stage "Install host dependencies"
warn "This installs Btrfs, partitioning, SMART, Samba, and SQLite runtime packages."
confirm "Install the required Debian packages now?" || exit 1
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends \
  btrfs-progs parted smartmontools samba libsqlite3-0

stage "Install root-owned A-NAS system services"
anas_uid=$(id -u anas-dev)
runtime_dir="/run/user/$anas_uid"
if [[ -S "$runtime_dir/bus" ]]; then
  runuser -u anas-dev -- env \
    XDG_RUNTIME_DIR="$runtime_dir" \
    DBUS_SESSION_BUS_ADDRESS="unix:path=$runtime_dir/bus" \
    systemctl --user disable --now anas-api.service anas-host-agent.service
else
  warn "anas-dev user bus is absent; verify no process still owns 127.0.0.1:8080"
fi
if ss -ltnp | grep -q '127\.0\.0\.1:8080'; then
  warn "port 127.0.0.1:8080 is still occupied"
  ss -ltnp | grep '127\.0\.0\.1:8080' || true
  exit 1
fi

target_release="/opt/a-nas/releases/$RELEASE_ID"
if [[ -e "$target_release" ]]; then
  [[ "$(readlink -f /opt/a-nas/current 2>/dev/null || true)" == "$target_release" ]] || {
    warn "target release already exists but is not current"
    exit 1
  }
  say "Root release is already installed; continuing verification."
else
  "$SOURCE_RELEASE/install-v1.0.1-system-services.sh" \
    "$SOURCE_RELEASE" "$RELEASE_ID" "$SMB_INTERFACE"
fi

systemctl is-active --quiet anas-host-agent.service
systemctl is-active --quiet anas-api.service
[[ "$(readlink -f /opt/a-nas/current)" == "$target_release" ]]
[[ "$(stat -c '%U:%G %a' /run/a-nas/host-agent.sock)" == "root:a-nas 660" ]]
ss -ltnp | grep '127\.0\.0\.1:8080'
say "System services are active and the Product Service remains loopback-only."

stage "Create the first administrator"
setup_status=$(python3 -c 'import urllib.request; print(urllib.request.urlopen("http://127.0.0.1:8080/api/v1/setup/status", timeout=5).read().decode())')
if [[ "$setup_status" == *'"setupRequired":true'* ]]; then
  step "At the local Kiosk, create the first administrator with only an account and password."
  step "The first account is the A-NAS product administrator; it is not the Linux root account."
  step "Use a new test-only password; the wizard never reads or stores it."
  pause "Press Enter only after the administrator has been created."
  setup_status=$(python3 -c 'import urllib.request; print(urllib.request.urlopen("http://127.0.0.1:8080/api/v1/setup/status", timeout=5).read().decode())')
fi
[[ "$setup_status" == *'"setupRequired":false'* ]] || { warn "first-run setup is still pending"; exit 1; }
say "Local device activation is complete."

stage "Create the confirmed Btrfs data volume"
if findmnt -rn -T /srv/a-nas/data -o FSTYPE | grep -qx btrfs; then
  say "The verified data mount already exists; skipping destructive UI instructions."
else
  warn "The next UI operation permanently erases the confirmed experimental disk."
  say "Expected WWN: $EXPECTED_DISK_WWN"
  say "Expected serial: $EXPECTED_DISK_SERIAL"
  say "Expected size: $EXPECTED_DISK_SIZE_BYTES bytes"
  step "Open Storage Initialization in the local Kiosk."
  step "Generate a plan and compare model, capacity, fingerprint, signatures, actions, and stable disk ID."
  step "Only when every value matches, enter the exact confirmation phrase and execute the plan."
  confirm "Do you understand that this UI action is irreversible?" || exit 1
  pause "Press Enter after the UI reports the storage operation succeeded."
fi

[[ "$(findmnt -rn -T /srv/a-nas/data -o FSTYPE)" == "btrfs" ]] || { warn "data volume is not mounted as Btrfs"; exit 1; }
[[ -f /srv/a-nas/data/.a-nas-volume.json ]] || { warn "data volume identity marker is missing"; exit 1; }
findmnt /srv/a-nas/data
btrfs filesystem show /srv/a-nas/data
say "The data volume is mounted and identity-marked."

stage "Exercise and capture the storage/share closure"
step "Create two member accounts and verify neither can list or read the other's personal space."
step "Upload a disposable large file through Web, download it, and compare SHA-256."
step "Write and read the same test set through Windows SMB at \\\\172.18.45.48\\Shared."
step "Delete through Web and SMB, then restore from Trash and compare SHA-256."
step "Create, browse, restore from, and delete a manual read-only snapshot."
pause "Press Enter after completing these closure checks."

testparm --suppress-prompt /etc/samba/smb.conf >/dev/null
systemctl is-active --quiet smbd.service anas-host-agent.service anas-api.service

evidence_dir=/var/lib/a-nas/acceptance
evidence_file="$evidence_dir/$RELEASE_ID.txt"
install -d -o root -g a-nas -m 0750 "$evidence_dir"
{
  date -Is
  printf 'release=%s\n' "$(readlink -f /opt/a-nas/current)"
  timedatectl status
  timedatectl timesync-status || true
  lsblk -e7 -o NAME,PATH,TYPE,SIZE,MODEL,SERIAL,WWN,TRAN,RM,HOTPLUG,FSTYPE,UUID,MOUNTPOINTS
  findmnt /srv/a-nas/data
  btrfs filesystem usage /srv/a-nas/data
  smartctl -H -A "$stable_disk" || true
  systemctl --no-pager --full status smbd.service anas-host-agent.service anas-api.service
} > "$evidence_file" 2>&1
chmod 0640 "$evidence_file"
say "Host acceptance evidence: $evidence_file"
warn "A normal reboot and post-boot UUID mount check remain before final v1.0.1 release."

finish
